### PR TITLE
force the enable call to allow many cisco ios platforms to work

### LINKED ISSUE #64: Netmiko nornir send_command needs enable=
https://github.com/nautobot/nornir-nautobot/blob/4d6a4da7388461b70a0115c00fd3cef1f768712f/nornir_nautobot/plugins/tasks/dispatcher/default.py#L237

Right now if you go into `>` mode on cisco_ios and you don't have permissions to run `show run` it isn't going to try the `DEVICE_SECRET` and go into enable mode to get the config.

The job itself shows successful but the backup itself in Git is saved as:
```
                      ^
% Invalid input detected at '^' marker.
```

### PR DESCRIPTION
**Pull request by jeffkala**
fixes #64 , forcing the enable call to true fixes multiple cisco_ios switches.

### CODE REVIEW

**Review by itdependsnetworks — APPROVED** [review]

**Review by jvanderaa — COMMENTED** [review]
Should we do this thru a setting instead of defaulting to true? This could cause some challenges.

**Comment by itdependsnetworks** [comment]
nornir-netmiko calls the enable method
https://github.com/ktbyers/nornir_netmiko/blob/develop/nornir_netmiko/tasks/netmiko_send_command.py#L27-L28

netmiko checks if it is enabled already
https://github.com/ktbyers/netmiko/blob/1c75ca31a13e2ab1844078a8e1b1fd5f77c51097/netmiko/base_connection.py#L2024-L2025

Would be good to ensure you have tested
* No enable required
* Enable required, Enable successful
* Enable required, no enable password provided

**Comment by jvanderaa** [comment]
I'm more so thinking through places that may provide the commands natively to the account that logs in, and disallows/alerts on someone issuing the command `enable`. So I would like to give them a method to disable the `enable` there. I'm generally OK if we have the default as `True`, but just want to provide a setting to disable this if nesseary.

**Comment by jvanderaa** [comment]
So something like `is_truthy(os.getenv("NAUTOBOT_ENABLE_DEFAULT", True))`

**Comment by jeffkala** [comment]
I'm open to whatever on this, I find we're getting setting bloat.

**Comment by jeffkala** [comment]
@jvanderaa added your suggestion.
@itdependsnetworks tested all the ones you asked for

- [x] No enable required
- [x] Enable required, Enable successful
- [x] Enable required, no enable password provided

Plus a few other tests and everything seems to be working as we'd expect.

**Review by jvanderaa — APPROVED** [review]

**Pull request merged**
